from pydantic import BaseModel, Field
from typing import Annotated


class ProductBase(BaseModel):
    """Base schema for product information"""

    ncm: Annotated[
        str | None,
        Field(
            default=None,
            title="Product NCM code",
            description="NCM code of the product",
            examples=["87032100"],
        ),
    ]

    final_description: Annotated[
        str,
        Field(
            title="Product Final descriptrion",
            description="Final description of the product by Embedding Model",
            # examples=[""],
        ),
    ]

    erp_code: Annotated[
        str,
        Field(
            title="A code by Tecsys",
            description="A code for a product generated by Tecsys",
        ),
    ]

    model_config = {
        "extra": "forbid",
        "str_strip_whitespace": True,
        "from_attributes": True,
    }


class ProductCreate(ProductBase):
    pass


class ProductUpdate(ProductBase):
    final_description: Annotated[
        str | None,
        Field(
            title="Product Final descriptrion",
            description="Final description of the product by Embedding Model",
        ),
    ]

    erp_code: Annotated[
        str | None,
        Field(
            title="A code by Tecsys",
            description="A code for a product generated by Tecsys",
        ),
    ]

    model_config = ProductBase.model_config


class ProductResponse(BaseModel):
    id: int
    ncm: str | None
    final_description: str
    erp_code: str

