"""fix-supplyer_produt-model-add-erp-column

Revision ID: 5a4bc7907d1d
Revises: 989cf7d1c21c
Create Date: 2025-09-22 21:05:07.205509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4bc7907d1d'
down_revision: Union[str, Sequence[str], None] = '989cf7d1c21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'products', ['ncm'])
    op.add_column('supplyer_products', sa.Column('erp_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplyer_products', 'erp_description')
    op.drop_constraint(None, 'products', type_='unique')
    # ### end Alembic commands ###
